export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_Fail = 'CREATE_POST_Fail'
export const CREATE_POST_RESET = 'CREATE_POST_RESET'