version: '3'
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    volumes:
      - mondo-db:/data/db 
      
volumes:
  mondo-db: